### ISSUE TITLE
Compromised API Key

### ISSUE THREAD

**Issue by yldbouk** [DeeDeeAich/verselocator#1]
An exposed API key is visible in your [commit history](https://github.com/DeeDeeAich/verselocator/commit/43bf942696f3b5a1af35f0112768cc91802a89b6#diff-5bc02cefb3ea9e27f1a6776eabd1935dR4). You may want to consider invalidating that key and generating a new one.

**Comment by pro6dog** [comment]
Agreed

**Comment by DeeDeeAich** [comment]
Got it. Thanks.
